version: "3"
volumes:
  db-data:
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.3.2
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "22181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:7.3.2
  #   container_name: kafka-1
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper

# TODO добавить сервисы

  # note-service:
  #   build:
  #     context: src/notes
  #     dockerfile: Dockerfile
  #   image: drstarland/testum-notes:1.0
  #   container_name: testum-notes
  #   environment:
  #     PORT: "8070"
  #   ports:
  #     - "8070:8070"
  #   depends_on:
  #     - postgres

  # flight-service:
  #   build:
  #     context: src/flights
  #     dockerfile: Dockerfile
  #   image: drstarland/testum-flights:1.0
  #   container_name: testum-flights
  #   environment:
  #     PORT: "8060"
  #   ports:
  #     - "8060:8060"
  #   depends_on:
  #     - postgres

  # bonus-service:
  #   build:
  #     context: src/bonus
  #     dockerfile: Dockerfile
  #   image: drstarland/testum-bonus:1.0
  #   container_name: testum-bonus
  #   environment:
  #     PORT: "8050"
  #   ports:
  #     - "8050:8050"

  # gateway-service:
  #   build:
  #     context: src/gateway
  #     dockerfile: Dockerfile
  #   image: drstarland/testum-gateway:1.0
  #   container_name: testum-gateway
  #   environment:
  #     PORT: "8080"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - flight-service
  #     - ticket-service
  #     - bonus-service


