testus-bonus:
  service:
    port: 8050
    image:
      name: drstarland/testus-bonus
      version: "1.0"
    database:
      name: privileges
      username: program
      password: test

testus-tasks:
  service:
    port: 8060
    image:
      name: drstarland/testus-tasks
      version: "1.0"
    database: 
      name: flights
      username: program
      password: test

testus-notes:
  service:
    port: 8050
    image:
      name: drstarland/testus-notes
      version: "1.0"
    database: 
      name: flights
      username: program
      password: test

testus-users:
  service:
    port: 8040
    image:
      name: drstarland/testus-users
      version: "1.0"
    database: 
      name: tickets
      username: program
      password: test

testus-gateway:
  service:
    port: 8080
    image:
      name: drstarland/testus-gateway
      version: "1.0"
    isGateway: true