name: Build Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and publish images
        timeout-minutes: 10
        run: |
          docker compose build
          docker compose push
      
      - name: Deploy
        run: |
          kubectl config set-cluster flights-service-cluster --server="$KUBE_HOST" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=flights-service-cluster --user=cloud_okteto_com-user --namespace="drstarland"
          kubectl config use-context default
          kubectl get pods
          cd k8s && helm upgrade --install --force --debug services services-chart/
          kubectl apply -f load-balancer.yaml
          sleep 45
          kubectl get pods
      # TODO build and run unit tests

#      - name: Build images
#        timeout-minutes: 10
#        run: docker compose build

#      - name: Run containers
#        timeout-minutes: 5
#        run: |
#          docker compose up -d
#          ./scripts/wait-script.sh
#        env:
#          WAIT_PORTS: 8080,8070,8060,8050

#      - name: GitHub auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: ""
#          homework_number: 1
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

#      - name: Stop containers
#        if: always()
#        continue-on-error: true
#        run: docker compose down -v
